### ISSUE TITLE
Be less prescriptive

### ISSUE THREAD

**Issue by oliverjam** [oliverjam/react-tamagotchi#2]
I would like to see a bit more variety in the projects this time—I think that we were forced to be reasonably prescriptive before so they could get something done in the shorter time. We should probably de-emphasise some of the specifics in the requirements (a lot of people didn't even know what a Tamagotchi was)

It might be good to have a couple of examples that are quite different to show that the project requirements shouldn't restrict them.

@zooeymiller would you be interested in building something that fits the requirements but is maybe different to the Tamagotchi? I was thinking something like [this Choo example](https://choo-animals.glitch.me) from the [Choo Handbook](https://handbook.choo.io/your-first-choo-app/) could be cool

**Comment by ZooeyMiller** [comment]
Yeah I can do something like that! Will work on it this weekend.
