### ISSUE TITLE
change in install script

### ISSUE THREAD

**Issue by ZooeyMiller** [oliverjam/react-tamagotchi#3]
`npm i -D parcel-bundler babel-transform-class-properties` -> `npm i -D parcel-bundler babel-plugin-transform-class-properties`

**Comment by oliverjam** [comment]
Yeah whoops. I'll update. Did everything else work okay for you?

**Comment by ZooeyMiller** [comment]
yep :) Though I added babel config in package.json, which causes a bug with the hot module replacement, I doubt anyone has done babel stuff before so they'll probs just follow it word for word, but might be worth noting that with parcel babel stuff _has_ to be in babelrc rather than package.json.

**Comment by oliverjam** [comment]
Is that true for Parcel in general or just the version we're using (which I think is a bit old now)

**Comment by ZooeyMiller** [comment]
Not 100% sure, it was a known issue in an issue on the parcel repo but I'll find out properly.

**Comment by oliverjam** [comment]
Not sure I'm a fan of this everything-in-package-json trend. I like my separate config files

**Comment by tspeed90** [comment]
Was just going through this workshop and noticed the babel-plugin-transform-class-properties install script is wrong and found this issue already raised for it. Just wanted to flag it again so it can be fixed in time for FAC14 React week. :smiley:

**Comment by oliverjam** [comment]
Thanks for reminding me! Not sure if we should leave this repo as it is or direct people to my cloneable [Minimal React setup](https://github.com/oliverjam/minimal-react-setup)
